---
title: "7. heatmaply"
output:
  html_document:
    code_folding: hide
    fig_caption: yes
    self_contained: yes
    toc: false
    fig_width: 10
    fig_height: 6
    depth: 3  # upto three depths of headings (specified by #, ## and ###)  

vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
suppressPackageStartupMessages({
    library("SummarizedExperiment")
    library("plotlyutils")
    library("heatmaply")
    library("limma")
})
```

- TCGA GBM data
- Glycolysis gene signature "correlated with IDH1 mutation in GBM" 
  taken from [Chen et al. (2017)](https://www.sciencedirect.com/science/article/pii/S1673852717301492)

```{r, fig.caption = "Correlation heatmap"}
## https://www.sciencedirect.com/science/article/pii/S1673852717301492
df <- colData(GBMdata)[, "subtype_IDH.status", drop = FALSE]
colnames(df) <- "IDH1 status"
gene_signature <- c("ALDOB",
    "ENO1",
    "GALM",
    "GAPDH",
    "HK2",
    "HK3",
    "LDHA",
    "LDHB",
    "PKLR")
raw_mat <- assay(GBMdata)
raw_median_mat <- sweep(raw_mat, 1, rowMedians(raw_mat))
heatmaply_cor(cor(raw_median_mat[gene_signature, ]),
    row_side_colors = df,
    plot_method = "plotly",
    showticklabels = c(FALSE, FALSE))
```

```{r}
voom_mat <- voomed_GBM$E
voom_median_mat <- sweep(voom_mat, 1, rowMedians(voom_mat))
max <- max(abs(voom_median_mat[gene_signature, ]))
heatmaply(t(voom_median_mat[gene_signature, ]),
    row_side_colors = df,
    showticklabels = c(TRUE, FALSE),
    limits = c(-max, max),
    plot_method = "plotly",
    col = cool_warm)
```
