---
title: "3. heatmaply"
author: "Alan O'Callaghan"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    fig_caption: yes
    self_contained: yes
    toc: true
    fig_width: 10
    fig_height: 6
    depth: 3  # upto three depths of headings (specified by #, ## and ###)  

vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, echo = FALSE}
suppressPackageStartupMessages(library("SummarizedExperiment"))
suppressPackageStartupMessages(library("plotlytalk"))
```

```{r, fig.caption = "Correlation heatmap"}

raw_mat <- assay(GBMdata)
raw_median_mat <- apply(raw_mat, 1, function(row) {
    row - median(row)
})
heatmaply_cor(cor(t(raw_median_mat)),
    showticklabels = c(FALSE, FALSE)  )
```

```{r, fig.caption = "Correlation heatmap"}
voom_mat <- voomed_GBM$E
voom_median_mat <- apply(voom_mat, 1, function(row) {
    row - median(row)
})

heatmaply_cor(cor(t(voom_median_mat)),
    distfun = function(x) as.dist(1 - cor(t(x))),
    showticklabels = c(FALSE, FALSE))
```
