---
title: "10. Scatter plot with dropdown menus"
output:
  html_document:
    code_folding: hide
    fig_caption: yes
    self_contained: yes
    toc: false
    fig_width: 10
    fig_height: 6
    depth: 3  # upto three depths of headings (specified by #, ## and ###)  
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
suppressPackageStartupMessages({
    library("plotlyutils")
    library("SummarizedExperiment")
    library("limma")
})
```

```{r}
pcs <- prcomp(t(voomed_GBM$E))
pc_data <- pcs$x

columns <- c(
    "subtype_IDH.status",
    "subtype_Age..years.at.diagnosis.",
    "subtype_Gender",
    "subtype_Pan.Glioma.RNA.Expression.Cluster",
    "ethnicity"
)
colours <- colData(GBMdata)[, columns, drop = FALSE]
colours <- as.data.frame(colours)
colours$TotalReads <- colSums(assay(GBMdata))


plot(
    pc_data[, 1], 
    pc_data[, 2], 
    col = as.factor(colours[[1]]),
    pch = 16,
    xlab = "PC1",
    ylab = "PC2")
legend(
    max(pc_data[, 1]) * 0.7,
    max(pc_data[, 2]) * 0.7,
    unique(colours[[1]]),
    pch = 16,
    col = unique(colours[[1]]))
```

```{r}
selectable_scatter_plot(pc_data, colours)
```


