---
title: "11. Histogram with dropdown menu for x variable"
output:
  html_document:
    code_folding: hide
    fig_caption: yes
    self_contained: yes
    toc: false
    fig_width: 10
    fig_height: 6
    depth: 3  # upto three depths of headings (specified by #, ## and ###)  
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
suppressPackageStartupMessages({
    library("plotlyutils")
    library("SummarizedExperiment")
})
```

```{r}
distributions <- c(
    "beta", 
    "chisq", 
    "exp", 
    "gamma", 
    "norm", 
    "logis")

data <- lapply(distributions, function(distribution) {
    fun <- get(paste0("r", distribution), mode = "function")
    args <- c(list(1000), rep(1, length(formals(fun)) - 1))
    suppressWarnings(out <- do.call(fun, args))
    out
})
data <- as.data.frame(data)
colnames(data) <- distributions

hist(data[[1]], breaks = "FD", main = "beta", xlab = "Value", freq = FALSE)
hist(data[[2]], breaks = "FD", main = "chisquare", xlab = "Value", freq = FALSE)

```

```{r}
selectable_histogram(
    data, 
    title = "Draws of 1,000 from different probability distributions",
    histnorm = "probability density")
```


